apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
  namespace: default
spec:
  secretName: web-tls
  dnsNames:
    - quanghuy-07.id.vn
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer